[theme]
primaryColor = "#25D366"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#31333F"

[browser]
# Memaksa server menampilkan judul kustom di browser & sistem Android PWA
gatherUsageStats = false
